DEVICE_PATH := device/kyocera/js202
BOARD_VENDOR := kyocera
BOARD_DEVICE := js202
BOARD_ROOT_EXTRA_FOLDERS := mnt,metadata
BOARD_SUPPRESS_SECURE_ERASE := true

#64bit
TARGET_BUILD_64BIT := true
TARGET_BOARD_SUFFIX := _64
TARGET_SUPPORTS_64_BIT_APPS := true
TARGET_IS_64_BIT := true
TARGET_USES_64_BIT_BINDER := true

#display
TARGET_SCREEN_HEIGHT := 1280
TARGET_SCREEN_WIDTH := 800
TARGET_SCREEN_DENSITY := 213

TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop

TARGET_OTA_ASSERT_DEVICE := SZJ202,js202
AB_OTA_UPDATER := false

# For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
DISABLE_ARTIFACT_PATH_REQUIREMENTS := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := generic
TARGET_CPU_SMP := true
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)
ARCH_ARM_HAVE_TLS_REGISTER := true


# Bootloader
TARGET_BOARD_PLATFORM := msm8937
TARGET_BOOTLOADER_BOARD_NAME := MSM8937
TARGET_NO_RADIOIMAGE := true
TARGET_NO_BOOTLOADER := true
TARGET_NO_FACTORYIMAGE:=true


# Kernel
BOARD_BOOTIMG_HEADER_VERSION := 1
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_CMDLINE += console=ttyMSM0,115200,n8 \
                       androidboot.console=ttyMSM0 \
                       androidboot.hardware=qcom \
                       msm_rtb.filter=0x237 \
                       ehci-hcd.park=3 \
                       lpm_levels.sleep_disabled=1 \
                       androidboot.bootdevice=7824900.sdhci \
                       earlycon=msm_serial_dm,0x78B0000 \
                       firmware_class.path=/vendor/firmware_mnt/image \
                       androidboot.usbconfigfs=true \
                       loop.max_part=7
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_KERNEL_SEPARATED_DTBO := true
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_KERNEL_SEPARATED_DTBO := 
endif

# Partitions
TARGET_USES_MKE2FS := true
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
BOARD_FLASH_BLOCK_SIZE := 131072 # (BOARD_KERNEL_PAGESIZE * 64)
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2709520384
TARGET_COPY_OUT_VENDOR := vendor

# Recovery
BOARD_INCLUDE_RECOVERY_DTBO := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# Verified Boot
BOARD_AVB_ENABLE := false
BOARD_VNDK_VERSION := current
BOARD_VNDK_RUNTIME_DISABLE := true

# OS
PLATFORM_SECURITY_PATCH := 2021-10-01
VENDOR_SECURITY_PATCH := 2021-10-01
PLATFORM_VERSION := 9.0.0
BOARD_OS_VERSION := 9.0.0
RECOVERY_SDCARD_ON_DATA := true
TW_INCLUDE_CRYPTO := true

# TWRP Configuration
TW_THEME := landscape_hdpi
TW_ROTATION := 270
TW_EXTRA_LANGUAGES := false
TW_DEFAULT_LANGUAGE := ja
TW_SCREEN_BLANK_ON_BOOT := true
TW_USE_EXTERNAL_STORAGE := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := false
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_LPTOOLS := true
TW_EXCLUDE_LPDUMP := true
TW_EXCLUDE_TZDATA := true
TW_EXCLUDE_PYTHON := true
TW_INCLUDE_DUMLOCK := false
TW_INCLUDE_NTFS_3G := false
# TW_EXCLUDE_ENCRYPTED_BACKUPS := true
TW_DEVICE_VERSION := $(shell date -u +" %F")
RECOVERY_TOUCHSCREEN_SWAP_Y := true
RECOVERY_TOUCHSCREEN_FLIP_XY := true
#include vendor/sts/a05ba/BoardConfigVendor.mk
